apiVersion: v1
kind: Service
metadata:
  name: {{ include "mqtt-proxy.fullname" . }}
  labels:
    {{- include "mqtt-proxy.labels" . | nindent 4 }}
    {{- with .Values.service.labels -}}
    {{ toYaml . | nindent 4 }}
    {{- end }}
{{- if .Values.service.annotations }}
  annotations:
{{ tpl (toYaml .Values.service.annotations) . | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.http.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.mqtt.port }}
      targetPort: mqtt
      protocol: TCP
      name: mqtt
  selector:
    {{- include "mqtt-proxy.selectorLabels" . | nindent 4 }}
