{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "mqtt-proxy.fullname" . }}
  labels:
    {{- include "mqtt-proxy.labels" . | nindent 4 }}
    {{- with .Values.serviceMonitor.labels -}}
    {{ toYaml . | nindent 4 }}
    {{- end }}
spec:
  endpoints:
    - port: http
      path: /metrics
      interval: {{ .Values.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    {{- include "mqtt-proxy.selectorLabels" . | nindent 4 }}
{{- end }}