name: build

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14
      - name: Run build
        run: make clean build
      - name: Run test
        run: make test
      - name: Build and push Docker image
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: grepplabs/mqtt-proxy
          tag_with_ref: true
          always_pull: true
          add_git_labels: true
      - name: Set goreleaser env varbiales
        run: |
          echo "::set-env name=REVISION::$(git describe --tags --always --dirty)"
          echo "::set-env name=BRANCH::$(git rev-parse --abbrev-ref HEAD)"
          echo "::set-env name=BUILD_DATE::$(date +'%Y.%m.%d-%H:%M:%S')"
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
