name: build

on:
  push:
    branches:
      - master
    tags:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14
      - name: Run build
        run: make clean build
      - name: Run test
        run: make test
      - name: Run docker build
        run: make docker-build