name: build

on:
  push:
    branches:
      - master
    tags:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14
      - name: Run build
        run: make clean build
      - name: Run test
        run: make test
      - name: Build and push Docker image
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: grepplabs/mqtt-proxy
          tag_with_ref: true
          always_pull: true
          add_git_labels: true
